import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "./globals.css";
import { Providers } from "~/components/providers";
import { server } from "~/server/trpc/server";

const geistSans = Geist({
  subsets: ["latin", "latin-ext"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const chats = await server.user.getChatsByUserId();
  const friends = await server.friend.getFriendsByUserId();
  const friendRequests = await server.friend.getFriendRequestsByUserId();

  return (
    <html lang="en" suppressHydrationWarning>
      <body className={geistSans.className}>
        <Providers
          chats={chats.data ?? []}
          friends={friends.data ?? []}
          friendRequests={friendRequests!.data ?? []}
        >
          {children}
        </Providers>
      </body>
    </html>
  );
}
